const videoSrc = "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4";

function picsum(seed, width = 900, height = 1200) {
  return `https://picsum.photos/seed/${seed}/${width}/${height}`;
}

function dateAt(index) {
  return new Date(Date.UTC(2026, 5, 24, 8, index * 7, 0)).toISOString();
}

const catalog = [
  {
    id: "charcoal-greenhouse",
    type: "image",
    title: "Charcoal Greenhouse",
    prompt: "Abstract charcoal greenhouse studio with glass panels and soft cyan mist",
    src: "/generated/charcoal-greenhouse.png",
    alt: "Generated charcoal greenhouse studio with translucent panels and muted cyan mist",
    tags: ["architecture", "building", "greenhouse", "garden", "glass", "night", "cyan", "house", "home", "structure", "design", "interior", "exterior", "plant", "plants", "nature", "green", "studio", "abstract", "modern", "minimal", "dark", "moody", "mist", "fog", "panel", "panels", "window", "windows", "city", "urban", "construction", "real estate", "property", "landscape", "outdoor", "indoor", "scene", "art", "blue", "teal", "cinematic", "editorial", "atmosphere", "calm", "quiet", "industrial", "geometric"],
    style: "Architectural",
    model: "Luma Detail",
    aspectRatio: "2 / 3",
    quality: "High",
  },
  {
    id: "rain-courtyard",
    type: "image",
    title: "Rain Courtyard",
    prompt: "Rain-lit minimalist courtyard with black stone and shallow reflective water",
    src: "/generated/rain-courtyard.png",
    alt: "Generated rain-lit courtyard with black stone, reflective water, and a frosted lantern",
    tags: ["architecture", "garden", "home", "courtyard", "rain", "water", "lantern", "house", "building", "stone", "outdoor", "exterior", "minimal", "modern", "design", "structure", "reflection", "night", "dark", "moody", "wet", "weather", "lighting", "light", "interior", "patio", "yard", "landscape", "urban", "city", "real estate", "property", "calm", "quiet", "zen", "japanese", "asian", "black", "abstract", "art", "scene", "cinematic", "editorial", "nature", "plants", "tranquil", "still", "studio"],
    style: "Architectural",
    model: "Luma Base",
    aspectRatio: "2 / 3",
    quality: "High",
  },
  {
    id: "ocean-observatory-video",
    type: "video",
    title: "Tide Observatory",
    prompt: "Slow luminous tide outside a dark ocean observatory window",
    src: videoSrc,
    poster: "/generated/ocean-observatory.png",
    alt: "Generated video preview of cyan waves seen through a dark observatory window",
    tags: ["video", "ocean", "water", "nature", "building", "window", "cinematic", "sea", "waves", "wave", "tide", "architecture", "structure", "house", "home", "interior", "dark", "night", "moody", "blue", "cyan", "landscape", "seascape", "coast", "coastal", "horizon", "sky", "atmosphere", "calm", "quiet", "motion", "movement", "footage", "clip", "scene", "art", "abstract", "minimal", "modern", "glass", "reflection", "weather", "outdoor", "travel", "nature scene", "editorial", "studio", "design"],
    style: "Cinematic",
    model: "Luma Motion",
    aspectRatio: "16 / 9",
    quality: "Balanced",
  },
  {
    id: "ceramic-cyan-study",
    type: "image",
    title: "Cyan Ceramic Study",
    prompt: "Matte black ceramic forms arranged with translucent cyan glass sheets",
    src: "/generated/ceramic-cyan-still-life.png",
    alt: "Generated still life of matte black ceramics with translucent cyan glass sheets",
    tags: ["product", "ceramic", "still life", "glass", "abstract", "studio", "object", "objects", "design", "art", "minimal", "modern", "black", "cyan", "blue", "color", "shape", "form", "texture", "material", "interior", "table", "surface", "decor", "decoration", "pottery", "craft", "handmade", "editorial", "commercial", "advertising", "clean", "simple", "geometric", "light", "lighting", "shadow", "reflection", "translucent", "sheet", "sheets", "composition", "arrangement", "fine art", "contemporary", "studio shot"],
    style: "Product",
    model: "Luma Detail",
    aspectRatio: "1 / 1",
    quality: "High",
  },
  {
    id: "cliffside-room",
    type: "image",
    title: "Cliffside Room",
    prompt: "Foggy cliffside glass reading room made of black metal and smoked glass",
    src: "/generated/cliffside-reading-room.png",
    alt: "Generated cliffside black metal reading room surrounded by pale sea mist",
    tags: ["architecture", "building", "home", "interior", "landscape", "mist", "sea", "house", "room", "glass", "metal", "structure", "design", "modern", "minimal", "cliff", "cliffside", "coast", "coastal", "ocean", "water", "fog", "weather", "moody", "dark", "black", "nature", "outdoor", "scenic", "view", "reading", "library", "books", "furniture", "real estate", "property", "exterior", "calm", "quiet", "isolated", "remote", "cinematic", "editorial", "art", "abstract", "sky", "atmosphere", "travel"],
    style: "Architectural",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "creative-desk",
    type: "image",
    title: "Creative Desk",
    prompt: "Overhead dark creative desk with cyan design tiles and graphite paper",
    src: "/generated/creative-desk.png",
    alt: "Generated overhead creative desk with graphite paper and translucent cyan design tiles",
    tags: ["product", "desk", "interior", "abstract", "workspace", "design", "office", "work", "table", "paper", "tiles", "cyan", "blue", "color", "studio", "flat lay", "overhead", "top view", "creative", "art", "stationery", "tools", "minimal", "modern", "dark", "graphite", "objects", "still life", "composition", "home office", "furniture", "decor", "editorial", "commercial", "advertising", "clean", "organized", "planning", "sketch", "drawing", "material", "texture", "background"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "4 / 5",
    quality: "Balanced",
  },
  {
    id: "sunlit-home-courtyard",
    type: "image",
    title: "Sunlit Home Courtyard",
    prompt: "Warm modern home courtyard with white walls, plants, and morning light",
    src: picsum("home-courtyard-garden", 900, 1200),
    alt: "Generated modern home courtyard with plants and morning light",
    tags: ["home", "house", "architecture", "building", "garden", "plants", "sunlight", "courtyard", "interior", "exterior", "structure", "design", "modern", "minimal", "white", "bright", "light", "morning", "outdoor", "patio", "yard", "nature", "green", "real estate", "property", "landscape", "wall", "walls", "scene", "calm", "quiet", "warm", "sunny", "day", "daylight", "tranquil", "residential", "lifestyle", "decor", "editorial", "travel", "leisure", "relax"],
    style: "Architectural",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "glass-city-tower",
    type: "image",
    title: "Glass City Tower",
    prompt: "Tall glass building in a bright downtown cityscape",
    src: picsum("glass-city-building", 1000, 1400),
    alt: "Generated glass tower in a bright cityscape",
    tags: ["building", "architecture", "city", "cityscape", "urban", "tower", "skyscraper", "glass", "structure", "design", "modern", "downtown", "office", "business", "real estate", "property", "sky", "bright", "daylight", "metropolitan", "skyline", "exterior", "facade", "corporate", "finance", "construction", "tall", "high rise", "reflection", "minimal", "clean", "editorial", "travel", "landscape", "outdoor", "scene", "day", "home", "house", "garden", "interior", "color", "art", "abstract", "photography"],
    style: "Architectural",
    model: "Luma Detail",
    aspectRatio: "5 / 7",
    quality: "High",
  },
  {
    id: "small-cabin-garden",
    type: "image",
    title: "Cabin Garden",
    prompt: "Small wooden cabin beside a green garden and stone path",
    src: picsum("small-cabin-garden", 900, 1300),
    alt: "Generated cabin with a green garden and stone path",
    tags: ["home", "house", "cabin", "garden", "nature", "plants", "landscape", "wood", "wooden", "architecture", "building", "structure", "rural", "countryside", "path", "stone", "outdoor", "exterior", "rustic", "cozy", "retreat", "cottage", "real estate", "property", "green", "trees", "forest", "scenic", "travel", "vacation", "calm", "quiet", "peaceful", "lifestyle", "residential", "design", "editorial", "season", "summer", "interior", "decor", "warm", "color"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "cinematic-red-car",
    type: "image",
    title: "Cinematic Red Car",
    prompt: "Low sports car on a wet road at sunset with cinematic reflections",
    src: picsum("cinematic-red-car-road", 1200, 800),
    alt: "Generated red sports car on a wet road at sunset",
    tags: ["car", "vehicle", "road", "transport", "cinematic", "sunset", "sports car", "automobile", "auto", "red", "color", "wet", "rain", "reflection", "drive", "driving", "speed", "luxury", "design", "transportation", "travel", "outdoor", "street", "evening", "sky", "light", "lighting", "moody", "dramatic", "editorial", "advertising", "commercial", "product", "lifestyle", "motion", "scene", "art", "performance", "horsepower", "sleek", "city", "urban"],
    style: "Cinematic",
    model: "Luma Detail",
    aspectRatio: "3 / 2",
    quality: "High",
  },
  {
    id: "blue-electric-car",
    type: "image",
    title: "Blue Electric Car",
    prompt: "Compact blue electric car parked near clean city architecture",
    src: picsum("blue-electric-car-city", 1200, 900),
    alt: "Generated blue electric car near modern city architecture",
    tags: ["car", "vehicle", "city", "building", "electric", "blue", "automobile", "auto", "transport", "transportation", "architecture", "urban", "modern", "clean", "design", "compact", "eco", "sustainable", "green energy", "parked", "street", "outdoor", "exterior", "product", "commercial", "advertising", "lifestyle", "travel", "color", "minimal", "studio", "editorial", "downtown", "structure", "road", "drive", "speed", "energy", "vehicle technology", "future", "innovation"],
    style: "Product",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "classic-car-video",
    type: "video",
    title: "Classic Car Pass",
    prompt: "Slow camera pass over a classic car in soft evening light",
    src: videoSrc,
    poster: picsum("classic-car-evening", 1200, 800),
    alt: "Generated video preview of a classic car in evening light",
    tags: ["video", "car", "classic", "vehicle", "cinematic", "evening", "automobile", "auto", "transport", "transportation", "vintage", "retro", "design", "light", "lighting", "moody", "footage", "clip", "scene", "motion", "movement", "travel", "luxury", "collector", "antique", "outdoor", "street", "road", "sky", "sunset", "dusk", "editorial", "advertising", "commercial", "art", "color", "warm", "city", "drive", "speed", "historic", "old", "style"],
    style: "Cinematic",
    model: "Luma Motion",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "city-taxi",
    type: "image",
    title: "City Taxi",
    prompt: "Yellow taxi car moving through a bright city street",
    src: picsum("city-taxi-car", 1200, 800),
    alt: "Generated yellow taxi car moving through a city street",
    tags: ["car", "taxi", "vehicle", "city", "street", "transport", "transportation", "automobile", "auto", "yellow", "color", "urban", "downtown", "bright", "daylight", "travel", "motion", "movement", "cab", "ride", "commute", "metropolitan", "outdoor", "road", "traffic", "editorial", "lifestyle", "scene", "building", "architecture", "drive", "driving", "passenger", "service", "modern", "speed", "busy", "everyday life", "people", "person"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "white-suv",
    type: "image",
    title: "White SUV",
    prompt: "White SUV car parked near a mountain road",
    src: picsum("white-suv-mountain-road", 1200, 800),
    alt: "Generated white SUV car parked near a mountain road",
    tags: ["car", "suv", "vehicle", "road", "mountain", "travel", "automobile", "auto", "transport", "transportation", "white", "color", "outdoor", "nature", "landscape", "parked", "adventure", "offroad", "scenic", "sky", "cinematic", "editorial", "advertising", "commercial", "product", "lifestyle", "family", "rugged", "design", "drive", "driving", "speed", "luxury", "modern", "studio", "city", "street", "trip", "journey", "people"],
    style: "Cinematic",
    model: "Luma Detail",
    aspectRatio: "3 / 2",
    quality: "High",
  },
  {
    id: "vintage-coupe",
    type: "image",
    title: "Vintage Coupe",
    prompt: "Vintage coupe car beside an old building in warm light",
    src: picsum("vintage-coupe-building", 1200, 900),
    alt: "Generated vintage coupe car beside an old building",
    tags: ["car", "coupe", "classic", "vehicle", "building", "warm", "automobile", "auto", "transport", "transportation", "vintage", "retro", "architecture", "old", "history", "historic", "street", "outdoor", "light", "lighting", "color", "design", "editorial", "lifestyle", "travel", "collector", "antique", "luxury", "scene", "urban", "drive", "speed", "city", "house", "road", "evening", "sunset", "style", "nature", "people"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "electric-sedan",
    type: "image",
    title: "Electric Sedan",
    prompt: "Electric sedan car in a clean product studio",
    src: picsum("electric-sedan-product", 1200, 900),
    alt: "Generated electric sedan car in a clean product studio",
    tags: ["car", "sedan", "electric", "vehicle", "product", "studio", "automobile", "auto", "transport", "transportation", "clean", "minimal", "design", "eco", "sustainable", "green energy", "commercial", "advertising", "lifestyle", "modern", "sleek", "luxury", "color", "background", "lighting", "reflection", "road", "drive", "speed", "city", "innovation", "technology", "future", "performance", "showroom", "exterior", "interior", "travel", "nature", "people"],
    style: "Product",
    model: "Luma Detail",
    aspectRatio: "4 / 3",
    quality: "High",
  },
  {
    id: "desert-truck",
    type: "image",
    title: "Desert Truck",
    prompt: "Truck car crossing a pale desert road under blue sky",
    src: picsum("desert-truck-road", 1200, 800),
    alt: "Generated truck car crossing a desert road",
    tags: ["car", "truck", "vehicle", "desert", "road", "travel", "automobile", "auto", "transport", "transportation", "nature", "landscape", "sky", "blue", "sand", "outdoor", "adventure", "offroad", "scenic", "rugged", "cinematic", "editorial", "advertising", "commercial", "lifestyle", "sunny", "day", "drive", "driving", "speed", "city", "house", "journey", "trip", "wilderness", "horizon", "dust", "remote", "people", "person"],
    style: "Cinematic",
    model: "Luma Base",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "family-car-driveway",
    type: "image",
    title: "Driveway Car",
    prompt: "Family car parked in a home driveway beside a small garden",
    src: picsum("family-car-driveway-garden", 1200, 900),
    alt: "Generated family car in a home driveway beside a garden",
    tags: ["car", "vehicle", "home", "driveway", "garden", "house", "automobile", "auto", "transport", "transportation", "family", "residential", "architecture", "building", "plants", "nature", "outdoor", "exterior", "real estate", "property", "lifestyle", "suburban", "parked", "calm", "quiet", "daylight", "editorial", "drive", "road", "street", "city", "neighborhood", "color", "design", "interior", "modern", "everyday life", "people", "person", "human"],
    style: "Architectural",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "mountain-bike-trail",
    type: "image",
    title: "Mountain Bike Trail",
    prompt: "Mountain bike leaning on a forest trail after rain",
    src: picsum("mountain-bike-forest-trail", 900, 1200),
    alt: "Generated mountain bike on a wet forest trail",
    tags: ["bike", "bicycle", "mountain bike", "nature", "forest", "trail", "outdoor", "sport", "sports", "adventure", "wet", "rain", "trees", "green", "landscape", "path", "travel", "lifestyle", "fitness", "exercise", "active", "leisure", "vehicle", "transport", "wood", "moody", "editorial", "scenic", "calm", "mountain", "hill", "hills", "wilderness", "ride", "riding", "speed", "extreme sport", "weather", "people", "person"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "city-bike",
    type: "image",
    title: "City Bike",
    prompt: "Simple commuter bike beside a bright cafe wall",
    src: picsum("city-bike-cafe-wall", 900, 1200),
    alt: "Generated commuter bike beside a bright cafe wall",
    tags: ["bike", "bicycle", "city", "street", "cafe", "transport", "transportation", "vehicle", "urban", "commuter", "commute", "lifestyle", "wall", "building", "architecture", "outdoor", "bright", "daylight", "color", "minimal", "editorial", "leisure", "travel", "design", "ride", "riding", "road", "modern", "simple", "drink", "coffee", "wall art", "scene", "everyday life", "nature", "people", "person", "human", "indoor", "art"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Draft",
  },
  {
    id: "bike-video-loop",
    type: "video",
    title: "Bike Path Loop",
    prompt: "Gentle moving shot along a bike path through a green park",
    src: videoSrc,
    poster: picsum("bike-path-green-park", 1200, 800),
    alt: "Generated video preview of a bike path through a green park",
    tags: ["video", "bike", "bicycle", "park", "garden", "nature", "path", "outdoor", "transport", "transportation", "vehicle", "green", "trees", "landscape", "footage", "clip", "scene", "motion", "movement", "leisure", "lifestyle", "travel", "calm", "quiet", "sunny", "daylight", "cinematic", "editorial", "exercise", "fitness", "ride", "riding", "sport", "active", "city", "road", "people", "person", "human", "indoor"],
    style: "Cinematic",
    model: "Luma Motion",
    aspectRatio: "16 / 9",
    quality: "Balanced",
  },
  {
    id: "white-flower-closeup",
    type: "image",
    title: "White Flower Closeup",
    prompt: "Close view of a white flower with soft green background",
    src: picsum("white-flower-closeup", 900, 1200),
    alt: "Generated white flower closeup with a soft green background",
    tags: ["flower", "flowers", "nature", "garden", "plant", "macro", "white", "color", "closeup", "petals", "bloom", "blossom", "botanical", "green", "background", "soft", "light", "lighting", "minimal", "studio", "art", "editorial", "decor", "spring", "summer", "still life", "detail", "fine art", "outdoor", "leaf", "leaves", "delicate", "fresh", "beauty", "natural", "calm", "people", "person", "human", "indoor"],
    style: "Nature",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "wildflower-field",
    type: "image",
    title: "Wildflower Field",
    prompt: "Open field of colorful wildflowers under a clear sky",
    src: picsum("wildflower-field-sky", 1200, 900),
    alt: "Generated wildflower field under a clear sky",
    tags: ["flower", "flowers", "nature", "landscape", "field", "colorful", "plant", "plants", "garden", "outdoor", "sky", "open", "meadow", "bloom", "blossom", "botanical", "color", "spring", "summer", "scenic", "travel", "calm", "quiet", "peaceful", "editorial", "sunny", "bright", "daylight", "green", "wild", "natural", "countryside", "rural", "wide", "beautiful", "people", "person", "human", "indoor", "scene"],
    style: "Nature",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "flower-video-study",
    type: "video",
    title: "Flower Study",
    prompt: "Slow video study of petals moving in a light breeze",
    src: videoSrc,
    poster: picsum("flower-petals-breeze", 900, 1200),
    alt: "Generated video preview of flower petals in a light breeze",
    tags: ["video", "flower", "flowers", "nature", "garden", "petals", "plant", "plants", "botanical", "bloom", "blossom", "footage", "clip", "scene", "motion", "movement", "breeze", "wind", "soft", "light", "lighting", "macro", "closeup", "color", "calm", "quiet", "cinematic", "editorial", "spring", "delicate", "fresh", "beauty", "natural", "outdoor", "white", "studio", "people", "person", "human", "indoor"],
    style: "Nature",
    model: "Luma Motion",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "botanical-garden",
    type: "image",
    title: "Botanical Garden",
    prompt: "Layered botanical garden with bright leaves and curved paths",
    src: picsum("botanical-garden-path", 900, 1200),
    alt: "Generated botanical garden with bright leaves and curved paths",
    tags: ["garden", "nature", "plants", "trees", "path", "green", "botanical", "leaves", "leaf", "outdoor", "landscape", "park", "foliage", "color", "bright", "scenic", "travel", "calm", "quiet", "peaceful", "editorial", "lush", "tropical", "design", "flower", "flowers", "bloom", "garden path", "natural", "season", "spring", "summer", "art", "architecture", "people", "person", "human", "indoor", "scene", "light"],
    style: "Nature",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "rooftop-garden",
    type: "image",
    title: "Rooftop Garden",
    prompt: "Rooftop garden with planters, city skyline, and soft afternoon light",
    src: picsum("rooftop-garden-city", 1200, 900),
    alt: "Generated rooftop garden with planters and city skyline",
    tags: ["garden", "city", "cityscape", "plants", "home", "building", "rooftop", "architecture", "structure", "urban", "skyline", "outdoor", "exterior", "nature", "green", "planters", "real estate", "property", "lifestyle", "afternoon", "light", "lighting", "design", "modern", "editorial", "calm", "flowers", "flower", "house", "interior", "downtown", "scenic", "leisure", "relax", "view", "people", "person", "human", "indoor", "scene"],
    style: "Architectural",
    model: "Luma Detail",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "forest-river",
    type: "image",
    title: "Forest River",
    prompt: "Clear river flowing through a green forest landscape",
    src: picsum("forest-river-landscape", 1200, 900),
    alt: "Generated forest river landscape",
    tags: ["nature", "forest", "river", "water", "landscape", "trees", "green", "outdoor", "scenic", "travel", "wilderness", "calm", "quiet", "peaceful", "stream", "flow", "rocks", "natural", "environment", "editorial", "cinematic", "garden", "plant", "plants", "mountain", "sky", "leaf", "leaves", "fresh", "summer", "spring", "wild", "remote", "people", "person", "human", "indoor", "scene", "art", "design"],
    style: "Nature",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "mountain-sunrise",
    type: "image",
    title: "Mountain Sunrise",
    prompt: "Mountain landscape at sunrise with soft clouds and warm color",
    src: picsum("mountain-sunrise-clouds", 1200, 800),
    alt: "Generated mountain landscape at sunrise",
    tags: ["nature", "mountain", "landscape", "sunrise", "clouds", "travel", "outdoor", "sky", "scenic", "warm", "color", "morning", "peak", "peaks", "range", "wilderness", "calm", "quiet", "peaceful", "cinematic", "editorial", "adventure", "hiking", "sun", "light", "lighting", "horizon", "natural", "rural", "countryside", "remote", "view", "snow", "rock", "people", "person", "human", "indoor", "scene", "art"],
    style: "Cinematic",
    model: "Luma Detail",
    aspectRatio: "3 / 2",
    quality: "High",
  },
  {
    id: "desert-landscape",
    type: "image",
    title: "Desert Light",
    prompt: "Wide desert landscape with clean sand forms and pale blue sky",
    src: picsum("desert-light-landscape", 1200, 800),
    alt: "Generated desert landscape with sand forms and pale blue sky",
    tags: ["nature", "desert", "landscape", "sand", "sky", "minimal", "outdoor", "scenic", "travel", "blue", "wide", "dune", "dunes", "arid", "barren", "calm", "quiet", "peaceful", "abstract", "editorial", "cinematic", "sun", "sunny", "heat", "wilderness", "remote", "natural", "horizon", "rock", "rocks", "warm", "color", "open", "people", "person", "human", "indoor", "scene", "art", "design"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "ocean-cliff",
    type: "image",
    title: "Ocean Cliff",
    prompt: "Blue ocean cliff with a small path and wind-shaped grass",
    src: picsum("ocean-cliff-path", 900, 1200),
    alt: "Generated ocean cliff with a small path and grass",
    tags: ["nature", "ocean", "sea", "landscape", "cliff", "water", "outdoor", "coast", "coastal", "scenic", "travel", "blue", "path", "grass", "wind", "horizon", "sky", "calm", "quiet", "peaceful", "cinematic", "editorial", "wilderness", "rock", "rocks", "beach", "waves", "wave", "natural", "view", "remote", "green", "people", "person", "human", "indoor", "scene", "art", "design", "color"],
    style: "Cinematic",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "portrait-girl-window",
    type: "image",
    title: "Window Portrait",
    prompt: "Portrait of a girl near a window with soft natural light",
    src: picsum("girl-window-portrait", 900, 1200),
    alt: "Generated portrait of a girl near a softly lit window",
    tags: ["girl", "portrait", "person", "people", "woman", "window", "soft light", "human", "face", "model", "fashion", "interior", "home", "indoor", "light", "lighting", "natural light", "editorial", "lifestyle", "calm", "quiet", "young", "female", "beauty", "studio", "photography", "art", "house", "room", "color", "warm", "portrait photography", "boy", "man", "nature", "outdoor", "scene", "design", "background", "travel"],
    style: "Portrait",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "portrait-girl-garden",
    type: "image",
    title: "Garden Portrait",
    prompt: "Portrait of a girl in a green garden with flowers behind her",
    src: picsum("girl-garden-portrait", 900, 1200),
    alt: "Generated portrait of a girl in a green garden",
    tags: ["girl", "portrait", "person", "garden", "flowers", "people", "woman", "human", "face", "model", "fashion", "nature", "plants", "green", "outdoor", "flower", "bloom", "editorial", "lifestyle", "young", "female", "beauty", "spring", "summer", "photography", "art", "color", "natural light", "soft light", "scenic", "calm", "boy", "man", "indoor", "scene", "design", "light", "lighting", "background", "travel"],
    style: "Portrait",
    model: "Luma Base",
    aspectRatio: "4 / 5",
    quality: "Balanced",
  },
  {
    id: "portrait-man-studio",
    type: "image",
    title: "Studio Portrait",
    prompt: "Portrait of a man in a clean studio with calm directional light",
    src: picsum("man-studio-portrait", 900, 1200),
    alt: "Generated portrait of a man in a clean studio",
    tags: ["man", "portrait", "person", "people", "studio", "editorial", "human", "face", "model", "fashion", "boy", "male", "indoor", "light", "lighting", "directional light", "clean", "minimal", "background", "photography", "art", "calm", "professional", "headshot", "color", "design", "modern", "studio shot", "girl", "woman", "nature", "outdoor", "scene", "travel", "lifestyle", "quiet", "landscape", "city", "urban", "building"],
    style: "Portrait",
    model: "Luma Detail",
    aspectRatio: "4 / 5",
    quality: "High",
  },
  {
    id: "man-city-walk",
    type: "image",
    title: "City Walk",
    prompt: "Man walking through a city street in clean evening light",
    src: picsum("man-city-walk", 900, 1200),
    alt: "Generated man walking through a city street",
    tags: ["man", "person", "people", "city", "street", "urban", "human", "boy", "male", "walking", "lifestyle", "evening", "light", "lighting", "outdoor", "downtown", "fashion", "editorial", "travel", "scene", "architecture", "building", "girl", "woman", "portrait", "color", "modern", "metropolitan", "road", "nature", "indoor", "art", "design", "background", "minimal", "calm", "quiet", "landscape", "home", "house"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "people-market",
    type: "image",
    title: "Market Morning",
    prompt: "People moving through a bright outdoor market in the morning",
    src: picsum("people-market-morning", 1200, 900),
    alt: "Generated people moving through an outdoor market",
    tags: ["people", "person", "market", "city", "street", "morning", "human", "crowd", "outdoor", "urban", "lifestyle", "shopping", "vendor", "stalls", "bright", "daylight", "travel", "editorial", "scene", "everyday life", "commerce", "man", "woman", "boy", "girl", "color", "downtown", "building", "nature", "indoor", "art", "design", "light", "lighting", "background", "modern", "minimal", "calm", "quiet", "landscape"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Draft",
  },
  {
    id: "portrait-video",
    type: "video",
    title: "Portrait Motion",
    prompt: "Subtle moving portrait with soft light and shallow focus",
    src: videoSrc,
    poster: picsum("portrait-motion-soft-light", 900, 1200),
    alt: "Generated video preview of a softly lit portrait",
    tags: ["video", "portrait", "person", "people", "girl", "man", "cinematic", "human", "face", "model", "fashion", "woman", "boy", "male", "female", "footage", "clip", "scene", "motion", "movement", "soft light", "shallow focus", "indoor", "studio", "editorial", "photography", "art", "color", "lighting", "calm", "nature", "outdoor", "design", "light", "background", "travel", "lifestyle", "modern", "minimal", "quiet"],
    style: "Portrait",
    model: "Luma Motion",
    aspectRatio: "4 / 5",
    quality: "Balanced",
  },
  {
    id: "warm-living-room",
    type: "image",
    title: "Warm Living Room",
    prompt: "Comfortable living room interior with plants and warm neutral fabric",
    src: picsum("warm-living-room-plants", 1200, 900),
    alt: "Generated warm living room interior with plants",
    tags: ["interior", "home", "room", "plants", "furniture", "warm", "house", "living room", "design", "architecture", "comfort", "cozy", "indoor", "decor", "lifestyle", "couch", "sofa", "fabric", "neutral", "nature", "green", "real estate", "property", "editorial", "calm", "light", "lighting", "color", "modern", "minimal", "people", "person", "human", "outdoor", "scene", "art", "background", "travel", "quiet", "landscape"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "minimal-kitchen",
    type: "image",
    title: "Minimal Kitchen",
    prompt: "Minimal kitchen interior with clean surfaces and morning sun",
    src: picsum("minimal-kitchen-sun", 1200, 900),
    alt: "Generated minimal kitchen with clean surfaces",
    tags: ["interior", "home", "kitchen", "architecture", "sunlight", "furniture", "house", "design", "minimal", "modern", "clean", "indoor", "decor", "lifestyle", "morning", "light", "lighting", "counter", "surfaces", "real estate", "property", "editorial", "bright", "color", "room", "structure", "calm", "nature", "people", "person", "human", "outdoor", "scene", "art", "background", "travel", "quiet", "landscape", "city", "urban"],
    style: "Architectural",
    model: "Luma Detail",
    aspectRatio: "4 / 3",
    quality: "High",
  },
  {
    id: "bedroom-blue",
    type: "image",
    title: "Blue Bedroom",
    prompt: "Quiet bedroom interior with blue bedding and soft daylight",
    src: picsum("blue-bedroom-daylight", 900, 1200),
    alt: "Generated quiet bedroom with blue bedding",
    tags: ["interior", "home", "bedroom", "blue", "room", "furniture", "house", "design", "color", "indoor", "decor", "lifestyle", "bed", "bedding", "calm", "quiet", "daylight", "light", "soft", "real estate", "property", "editorial", "modern", "minimal", "architecture", "structure", "nature", "people", "person", "human", "outdoor", "scene", "art", "lighting", "background", "travel", "landscape", "city", "urban", "building"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "city-night-street",
    type: "image",
    title: "City Night Street",
    prompt: "Night city street with wet pavement, signs, and cinematic reflections",
    src: picsum("city-night-street-reflections", 900, 1200),
    alt: "Generated night city street with cinematic reflections",
    tags: ["city", "cityscape", "street", "urban", "night", "cinematic", "building", "architecture", "wet", "rain", "reflection", "signs", "lights", "lighting", "dark", "moody", "downtown", "travel", "editorial", "scene", "atmosphere", "road", "color", "metropolitan", "structure", "exterior", "nature", "people", "person", "human", "outdoor", "indoor", "art", "design", "light", "background", "lifestyle", "modern", "minimal", "calm"],
    style: "Cinematic",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "bright-cityscape",
    type: "image",
    title: "Bright Cityscape",
    prompt: "Bright city skyline with a river and clean blue sky",
    src: picsum("bright-cityscape-river", 1200, 800),
    alt: "Generated city skyline with a river and blue sky",
    tags: ["city", "cityscape", "building", "river", "sky", "urban", "architecture", "skyline", "downtown", "water", "blue", "bright", "daylight", "metropolitan", "real estate", "property", "travel", "editorial", "landscape", "outdoor", "structure", "exterior", "modern", "design", "color", "scenic", "nature", "people", "person", "human", "indoor", "scene", "art", "light", "lighting", "background", "lifestyle", "minimal", "calm", "quiet"],
    style: "Architectural",
    model: "Luma Base",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "subway-motion-video",
    type: "video",
    title: "Subway Motion",
    prompt: "Moving city subway platform with cinematic light streaks",
    src: videoSrc,
    poster: picsum("subway-motion-city", 1200, 800),
    alt: "Generated video preview of a city subway platform",
    tags: ["video", "city", "urban", "transport", "subway", "cinematic", "transportation", "footage", "clip", "scene", "motion", "movement", "light streaks", "lighting", "platform", "train", "metro", "underground", "travel", "editorial", "downtown", "architecture", "structure", "color", "modern", "dark", "nature", "people", "person", "human", "outdoor", "indoor", "art", "design", "light", "background", "lifestyle", "minimal", "calm", "quiet"],
    style: "Cinematic",
    model: "Luma Motion",
    aspectRatio: "16 / 9",
    quality: "Balanced",
  },
  {
    id: "cat-window",
    type: "image",
    title: "Cat at Window",
    prompt: "Calm cat sitting near a window with soft indoor light",
    src: picsum("cat-window-soft-light", 900, 1200),
    alt: "Generated cat near a softly lit window",
    tags: ["animal", "cat", "pet", "home", "window", "interior", "kitten", "feline", "domestic", "indoor", "house", "light", "lighting", "soft light", "calm", "quiet", "cute", "lifestyle", "editorial", "nature", "color", "room", "furniture", "design", "warm", "natural light", "people", "person", "human", "outdoor", "scene", "art", "background", "travel", "modern", "minimal", "landscape", "city", "urban", "building"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "dog-park",
    type: "image",
    title: "Dog in Park",
    prompt: "Happy dog running through a green park in clear light",
    src: picsum("dog-green-park", 1200, 900),
    alt: "Generated dog running through a green park",
    tags: ["animal", "dog", "pet", "park", "nature", "green", "puppy", "canine", "domestic", "outdoor", "running", "happy", "playful", "lifestyle", "editorial", "sunny", "daylight", "grass", "landscape", "garden", "color", "summer", "spring", "active", "fun", "people", "person", "human", "indoor", "scene", "art", "design", "light", "lighting", "background", "travel", "modern", "minimal", "calm", "quiet"],
    style: "Nature",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "horse-field",
    type: "image",
    title: "Horse Field",
    prompt: "Horse standing in a wide field with soft clouds overhead",
    src: picsum("horse-field-clouds", 1200, 800),
    alt: "Generated horse standing in a wide field",
    tags: ["animal", "horse", "field", "nature", "landscape", "clouds", "outdoor", "farm", "rural", "countryside", "sky", "wildlife", "wild", "scenic", "travel", "editorial", "calm", "quiet", "open", "grass", "green", "natural", "majestic", "color", "people", "person", "human", "indoor", "scene", "art", "design", "light", "lighting", "background", "lifestyle", "modern", "minimal", "city", "urban", "building"],
    style: "Nature",
    model: "Luma Detail",
    aspectRatio: "3 / 2",
    quality: "High",
  },
  {
    id: "abstract-glass",
    type: "image",
    title: "Glass Geometry",
    prompt: "Abstract glass geometry with layered reflections and cool color",
    src: picsum("abstract-glass-geometry", 900, 1200),
    alt: "Generated abstract glass geometry with cool reflections",
    tags: ["abstract", "glass", "geometry", "blue", "reflection", "minimal", "art", "design", "color", "shape", "form", "texture", "modern", "studio", "background", "pattern", "cool", "editorial", "contemporary", "geometric", "light", "lighting", "clean", "product", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "travel", "lifestyle", "calm", "quiet", "landscape", "city", "urban", "building", "architecture"],
    style: "Abstract",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "abstract-paper",
    type: "image",
    title: "Paper Forms",
    prompt: "Abstract folded paper forms in coral, cream, and slate",
    src: picsum("abstract-paper-forms", 900, 1200),
    alt: "Generated abstract folded paper forms",
    tags: ["abstract", "paper", "color", "forms", "product", "studio", "art", "design", "shape", "texture", "minimal", "background", "pattern", "coral", "cream", "slate", "editorial", "contemporary", "still life", "geometric", "clean", "object", "material", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "light", "lighting", "travel", "lifestyle", "modern", "calm", "quiet", "landscape", "city", "urban"],
    style: "Abstract",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "color-wave",
    type: "image",
    title: "Color Wave",
    prompt: "Soft abstract wave of teal, amber, and gray in a clean frame",
    src: picsum("abstract-color-wave", 1200, 900),
    alt: "Generated abstract color wave in teal amber and gray",
    tags: ["abstract", "color", "teal", "amber", "gray", "wave", "art", "design", "pattern", "background", "minimal", "soft", "shape", "form", "texture", "editorial", "contemporary", "geometric", "clean", "studio", "product", "color wave", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "light", "lighting", "travel", "lifestyle", "modern", "calm", "quiet", "landscape", "city", "urban", "building"],
    style: "Abstract",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Draft",
  },
  {
    id: "watch-product-shot",
    type: "image",
    title: "Watch Product Shot",
    prompt: "Clean product shot of a simple watch on a stone surface",
    src: picsum("watch-product-stone", 900, 1200),
    alt: "Generated product shot of a watch on stone",
    tags: ["product", "watch", "stone", "studio", "minimal", "object", "design", "accessory", "fashion", "luxury", "clean", "background", "lighting", "commercial", "advertising", "editorial", "still life", "color", "modern", "material", "texture", "craft", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "art", "light", "travel", "lifestyle", "calm", "quiet", "landscape", "city", "urban", "building", "architecture"],
    style: "Product",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "sneaker-product",
    type: "image",
    title: "Sneaker Product",
    prompt: "Clean sneaker product photo with a colorful backdrop",
    src: picsum("sneaker-product-color", 1200, 900),
    alt: "Generated sneaker product photo with colorful backdrop",
    tags: ["product", "shoe", "sneaker", "fashion", "color", "studio", "object", "design", "footwear", "lifestyle", "clean", "background", "lighting", "commercial", "advertising", "editorial", "still life", "modern", "material", "style", "sport", "sports", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "art", "light", "travel", "minimal", "calm", "quiet", "landscape", "city", "urban", "building", "architecture"],
    style: "Product",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "chair-product",
    type: "image",
    title: "Chair Study",
    prompt: "Modern chair product study in a clean interior corner",
    src: picsum("chair-product-interior", 900, 1200),
    alt: "Generated modern chair product study",
    tags: ["product", "chair", "interior", "furniture", "home", "studio", "object", "design", "modern", "house", "decor", "clean", "minimal", "commercial", "advertising", "editorial", "still life", "room", "architecture", "material", "wood", "comfort", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "art", "color", "light", "lighting", "background", "travel", "lifestyle", "calm", "quiet", "landscape", "city"],
    style: "Product",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "food-table",
    type: "image",
    title: "Table Spread",
    prompt: "Fresh table spread with fruit, glassware, and bright daylight",
    src: picsum("fresh-table-spread", 1200, 900),
    alt: "Generated table spread with fruit and glassware",
    tags: ["food", "product", "table", "fruit", "interior", "daylight", "drink", "glassware", "fresh", "still life", "home", "kitchen", "lifestyle", "bright", "light", "editorial", "commercial", "advertising", "decor", "color", "warm", "meal", "dining", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "art", "design", "lighting", "background", "travel", "modern", "minimal", "calm", "quiet", "landscape"],
    style: "Editorial",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "fashion-editorial",
    type: "image",
    title: "Fashion Editorial",
    prompt: "Editorial fashion image with structured coat and city background",
    src: picsum("fashion-editorial-city", 900, 1200),
    alt: "Generated fashion editorial with structured coat and city background",
    tags: ["fashion", "portrait", "person", "city", "editorial", "people", "human", "model", "woman", "man", "clothing", "coat", "style", "urban", "street", "background", "architecture", "building", "lifestyle", "photography", "art", "girl", "boy", "color", "modern", "nature", "outdoor", "indoor", "scene", "design", "light", "lighting", "travel", "minimal", "calm", "quiet", "landscape", "home", "house", "garden"],
    style: "Editorial",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "beach-cinematic-video",
    type: "video",
    title: "Beach Drift",
    prompt: "Slow cinematic drift across a beach at blue hour",
    src: videoSrc,
    poster: picsum("beach-blue-hour", 1200, 800),
    alt: "Generated video preview of a beach at blue hour",
    tags: ["video", "beach", "ocean", "nature", "landscape", "cinematic", "sea", "water", "sand", "coast", "coastal", "footage", "clip", "scene", "motion", "movement", "blue hour", "dusk", "evening", "sky", "calm", "quiet", "travel", "editorial", "color", "horizon", "wave", "waves", "people", "person", "human", "outdoor", "indoor", "art", "design", "light", "lighting", "background", "lifestyle", "modern"],
    style: "Cinematic",
    model: "Luma Motion",
    aspectRatio: "16 / 9",
    quality: "High",
  },
  {
    id: "garden-home-video",
    type: "video",
    title: "Garden Home Pan",
    prompt: "Slow pan across a small home garden in afternoon light",
    src: videoSrc,
    poster: picsum("garden-home-pan", 1200, 800),
    alt: "Generated video preview of a small home garden",
    tags: ["video", "home", "garden", "plants", "house", "nature", "footage", "clip", "scene", "motion", "movement", "outdoor", "architecture", "real estate", "property", "afternoon", "light", "lighting", "green", "editorial", "calm", "flower", "flowers", "design", "structure", "exterior", "people", "person", "human", "indoor", "art", "color", "background", "travel", "lifestyle", "modern", "minimal", "quiet", "landscape", "city"],
    style: "Architectural",
    model: "Luma Motion",
    aspectRatio: "16 / 9",
    quality: "Balanced",
  },
  {
    id: "motorcycle-road",
    type: "image",
    title: "Motorcycle Road",
    prompt: "Motorcycle parked on a quiet road near hills",
    src: picsum("motorcycle-road-hills", 1200, 800),
    alt: "Generated motorcycle parked on a road near hills",
    tags: ["bike", "motorcycle", "vehicle", "road", "hills", "transport", "transportation", "automobile", "auto", "outdoor", "nature", "landscape", "travel", "adventure", "scenic", "parked", "editorial", "cinematic", "drive", "riding", "speed", "color", "sky", "mountain", "people", "person", "human", "indoor", "scene", "art", "design", "light", "lighting", "background", "lifestyle", "modern", "minimal", "calm", "quiet", "city"],
    style: "Cinematic",
    model: "Luma Base",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "train-landscape",
    type: "image",
    title: "Train Landscape",
    prompt: "Train moving through a wide green landscape",
    src: picsum("train-green-landscape", 1200, 800),
    alt: "Generated train moving through a green landscape",
    tags: ["train", "transport", "transportation", "nature", "landscape", "green", "travel", "vehicle", "outdoor", "railway", "rail", "scenic", "motion", "movement", "cinematic", "editorial", "sky", "color", "speed", "journey", "trip", "field", "people", "person", "human", "indoor", "scene", "art", "design", "light", "lighting", "background", "lifestyle", "modern", "minimal", "calm", "quiet", "city", "urban", "building"],
    style: "Cinematic",
    model: "Luma Base",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "library-interior",
    type: "image",
    title: "Library Interior",
    prompt: "Quiet library interior with tall shelves and soft amber light",
    src: picsum("library-interior-shelves", 900, 1200),
    alt: "Generated library interior with tall shelves",
    tags: ["interior", "library", "building", "home", "books", "warm", "architecture", "structure", "shelves", "indoor", "design", "calm", "quiet", "amber", "light", "lighting", "education", "reading", "editorial", "real estate", "room", "wood", "color", "nature", "people", "person", "human", "outdoor", "scene", "art", "background", "travel", "lifestyle", "modern", "minimal", "landscape", "city", "urban", "house", "garden"],
    style: "Architectural",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "bridge-city",
    type: "image",
    title: "Bridge City",
    prompt: "Large bridge crossing a river toward a bright city skyline",
    src: picsum("bridge-city-river", 1200, 800),
    alt: "Generated bridge crossing a river toward a city skyline",
    tags: ["bridge", "city", "cityscape", "river", "building", "architecture", "structure", "urban", "skyline", "water", "downtown", "travel", "real estate", "property", "bright", "daylight", "editorial", "landscape", "outdoor", "design", "color", "scenic", "nature", "people", "person", "human", "indoor", "scene", "art", "light", "lighting", "background", "lifestyle", "modern", "minimal", "calm", "quiet", "home", "house", "garden"],
    style: "Architectural",
    model: "Luma Base",
    aspectRatio: "3 / 2",
    quality: "Balanced",
  },
  {
    id: "snow-forest",
    type: "image",
    title: "Snow Forest",
    prompt: "Quiet snow forest with pale winter light and tall trees",
    src: picsum("snow-forest-winter", 900, 1200),
    alt: "Generated quiet snow forest with winter light",
    tags: ["nature", "forest", "snow", "winter", "trees", "landscape", "outdoor", "cold", "white", "scenic", "travel", "calm", "quiet", "peaceful", "wilderness", "editorial", "cinematic", "color", "season", "remote", "natural", "people", "person", "human", "indoor", "scene", "art", "design", "light", "lighting", "background", "lifestyle", "modern", "minimal", "city", "urban", "building", "architecture", "home", "house"],
    style: "Nature",
    model: "Luma Detail",
    aspectRatio: "3 / 4",
    quality: "High",
  },
  {
    id: "lake-house",
    type: "image",
    title: "Lake House",
    prompt: "Small lake house surrounded by trees and soft evening water",
    src: picsum("lake-house-evening", 1200, 900),
    alt: "Generated lake house surrounded by trees and evening water",
    tags: ["home", "house", "lake", "water", "nature", "architecture", "building", "structure", "trees", "outdoor", "exterior", "real estate", "property", "evening", "light", "lighting", "calm", "quiet", "scenic", "travel", "editorial", "color", "garden", "design", "people", "person", "human", "indoor", "scene", "art", "background", "lifestyle", "modern", "minimal", "landscape", "city", "urban", "plant", "plants", "animal"],
    style: "Architectural",
    model: "Luma Detail",
    aspectRatio: "4 / 3",
    quality: "High",
  },
  {
    id: "drone-farm",
    type: "image",
    title: "Green Fields",
    prompt: "Aerial view of green farm fields with clean geometric patterns",
    src: picsum("drone-green-fields", 1200, 900),
    alt: "Generated aerial view of green farm fields",
    tags: ["nature", "landscape", "field", "green", "aerial", "abstract", "farm", "rural", "countryside", "outdoor", "pattern", "geometric", "drone", "top view", "scenic", "travel", "editorial", "agriculture", "color", "minimal", "wide", "people", "person", "human", "indoor", "scene", "art", "design", "light", "lighting", "background", "lifestyle", "modern", "calm", "quiet", "city", "urban", "building", "architecture", "home"],
    style: "Abstract",
    model: "Luma Base",
    aspectRatio: "4 / 3",
    quality: "Balanced",
  },
  {
    id: "coffee-product",
    type: "image",
    title: "Coffee Product",
    prompt: "Coffee cup product shot with beans and morning window light",
    src: picsum("coffee-product-window", 900, 1200),
    alt: "Generated coffee cup product shot with beans",
    tags: ["product", "coffee", "cup", "food", "home", "morning", "drink", "beans", "still life", "window", "light", "lighting", "interior", "kitchen", "lifestyle", "commercial", "advertising", "editorial", "warm", "color", "studio", "design", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "art", "background", "travel", "modern", "minimal", "calm", "quiet", "landscape", "city", "urban", "building"],
    style: "Product",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Balanced",
  },
  {
    id: "orange-building",
    type: "image",
    title: "Orange Building",
    prompt: "Colorful orange building facade with strong graphic shadows",
    src: picsum("orange-building-facade", 900, 1200),
    alt: "Generated orange building facade with graphic shadows",
    tags: ["building", "architecture", "city", "orange", "color", "facade", "structure", "urban", "design", "shadows", "graphic", "exterior", "real estate", "property", "editorial", "abstract", "bright", "downtown", "modern", "nature", "people", "person", "human", "outdoor", "indoor", "scene", "art", "light", "lighting", "background", "travel", "lifestyle", "minimal", "calm", "quiet", "landscape", "home", "house", "garden", "plant"],
    style: "Architectural",
    model: "Luma Base",
    aspectRatio: "3 / 4",
    quality: "Draft",
  },
  {
    id: "meadow-girl-video",
    type: "video",
    title: "Meadow Portrait",
    prompt: "Soft moving portrait of a girl in a meadow with flowers",
    src: videoSrc,
    poster: picsum("girl-meadow-flowers-video", 900, 1200),
    alt: "Generated video preview of a girl in a meadow with flowers",
    tags: ["video", "girl", "portrait", "person", "flower", "flowers", "nature", "human", "face", "model", "woman", "female", "young", "meadow", "field", "outdoor", "footage", "clip", "scene", "motion", "movement", "bloom", "soft", "light", "lighting", "editorial", "lifestyle", "boy", "man", "people", "indoor", "art", "design", "color", "background", "travel", "modern", "minimal", "calm", "quiet"],
    style: "Portrait",
    model: "Luma Motion",
    aspectRatio: "4 / 5",
    quality: "Balanced",
  },
  {
    id: "abstract-product-video",
    type: "video",
    title: "Object Rotation",
    prompt: "Slow rotating product object on a clean abstract background",
    src: videoSrc,
    poster: picsum("abstract-product-rotation", 900, 900),
    alt: "Generated video preview of a product object rotating",
    tags: ["video", "product", "abstract", "object", "studio", "motion", "footage", "clip", "scene", "movement", "rotation", "background", "clean", "minimal", "design", "commercial", "advertising", "editorial", "color", "art", "modern", "nature", "people", "person", "human", "outdoor", "indoor", "light", "lighting", "travel", "lifestyle", "calm", "quiet", "landscape", "city", "urban", "building", "architecture", "home", "house"],
    style: "Product",
    model: "Luma Motion",
    aspectRatio: "1 / 1",
    quality: "Balanced",
  },
];

export const generatedContent = catalog.map((item, index) => ({
  ...item,
  createdAt: dateAt(index),
}));
