export const generatedContent = [
  {
    id: "img-charcoal-greenhouse",
    type: "image",
    title: "Charcoal Greenhouse",
    prompt: "Abstract charcoal greenhouse studio with glass panels and soft cyan mist",
    src: "/generated/charcoal-greenhouse.png",
    alt: "Generated charcoal greenhouse studio with translucent panels and muted cyan mist",
    createdAt: "2026-06-24T08:10:00.000Z",
    aspectRatio: "2 / 3",
  },
  {
    id: "img-rain-courtyard",
    type: "image",
    title: "Rain Courtyard",
    prompt: "Rain-lit minimalist courtyard with black stone and shallow reflective water",
    src: "/generated/rain-courtyard.png",
    alt: "Generated rain-lit courtyard with black stone, reflective water, and a frosted lantern",
    createdAt: "2026-06-24T08:16:00.000Z",
    aspectRatio: "2 / 3",
  },
  {
    id: "vid-tide-observatory",
    type: "video",
    title: "Tide Observatory",
    prompt: "Slow luminous tide outside a dark ocean observatory window",
    src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    poster: "/generated/ocean-observatory.png",
    alt: "Generated video preview of cyan waves seen through a dark observatory window",
    createdAt: "2026-06-24T08:22:00.000Z",
    aspectRatio: "16 / 9",
  },
  {
    id: "img-ceramic-cyan",
    type: "image",
    title: "Cyan Ceramic Study",
    prompt: "Matte black ceramic forms arranged with translucent cyan glass sheets",
    src: "/generated/ceramic-cyan-still-life.png",
    alt: "Generated still life of matte black ceramics with translucent cyan glass sheets",
    createdAt: "2026-06-24T08:29:00.000Z",
    aspectRatio: "1 / 1",
  },
  {
    id: "img-cliffside-room",
    type: "image",
    title: "Cliffside Room",
    prompt: "Foggy cliffside glass reading room made of black metal and smoked glass",
    src: "/generated/cliffside-reading-room.png",
    alt: "Generated cliffside black metal reading room surrounded by pale sea mist",
    createdAt: "2026-06-24T08:37:00.000Z",
    aspectRatio: "3 / 4",
  },
  {
    id: "img-creative-desk",
    type: "image",
    title: "Creative Desk",
    prompt: "Overhead dark creative desk with cyan design tiles and graphite paper",
    src: "/generated/creative-desk.png",
    alt: "Generated overhead creative desk with graphite paper and translucent cyan design tiles",
    createdAt: "2026-06-24T08:45:00.000Z",
    aspectRatio: "4 / 5",
  },
  {
    id: "vid-glass-lantern",
    type: "video",
    title: "Glass Lantern Loop",
    prompt: "A quiet lantern reflection moving across black stone after rain",
    src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    poster: "/generated/rain-courtyard.png",
    alt: "Generated video preview of lantern light reflecting across rain-dark stone",
    createdAt: "2026-06-24T08:52:00.000Z",
    aspectRatio: "3 / 4",
  },
  {
    id: "img-observatory-still",
    type: "image",
    title: "Ocean Window",
    prompt: "Dark observatory interior with a low horizon and soft marine cyan light",
    src: "/generated/ocean-observatory.png",
    alt: "Generated ocean observatory window with soft cyan marine light",
    createdAt: "2026-06-24T09:00:00.000Z",
    aspectRatio: "3 / 2",
  },
  {
    id: "img-smoked-glass",
    type: "image",
    title: "Smoked Glass Frame",
    prompt: "Black metal architecture floating above mist with a cyan glass tint",
    src: "/generated/cliffside-reading-room.png",
    alt: "Generated smoked glass architectural frame floating above pale mist",
    createdAt: "2026-06-24T09:08:00.000Z",
    aspectRatio: "5 / 6",
  },
  {
    id: "vid-desk-scan",
    type: "video",
    title: "Desk Scan",
    prompt: "A slow overhead camera pass across graphite paper and cyan design tiles",
    src: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
    poster: "/generated/creative-desk.png",
    alt: "Generated video preview of a dark creative desk with cyan design tiles",
    createdAt: "2026-06-24T09:16:00.000Z",
    aspectRatio: "4 / 5",
  },
];
